# Generated by Django 4.2.11 on 2024-05-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contact_number_userprofile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
