# Generated by Django 4.2.11 on 2024-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
