# Generated by Django 4.2.11 on 2024-05-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
